round temperature to nearest whole number
gwg-women/gwg-women-techmakers pull request #199
Opened 2018-04-19 23:57 UTC by M0nica

##Issue Number: [https://github.com/gwg-women/gwg-women-techmakers/issues/101](https://github.com/gwg-women/gwg-women-techmakers/issues/101
)
## Description
Added Math.round() to weather to make sure that it is rounded to the nearest whole number 

##Do any new issues need to be created as a result of this PR"?

No.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

🚨Please review the [contribution guidelines](https://github.com/gwg-women/gwg-women-techmakers/wiki/Contribution-Guidelines) to this repository.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Created a new branch from 'dev' and PR is targeting the project's 'dev' branch.
- [ ] The issue can be closed.

 Provide a descriptive branch name and once the pull request is approved and merged to dev, the branch can be deleted.

💔Thank you!

2018-04-20 01:03 UTC, digilou requested changes
It appears to have conflicts in the Header.js...?

2018-05-16 11:12 UTC, M0nica commented
@digilou @sgluzins Can you check to see if it is able to merge now? I attempted to resolve the merge conflict.

2018-05-16 15:01 UTC, digilou approved these changes

2018-05-25 05:44 UTC, sgluzins approved these changes

2018-05-25 10:39 UTC, merged